# Generated by Django 3.2.9 on 2021-11-18 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20211115_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['client']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date']},
        ),
        migrations.AlterModelOptions(
            name='eventstatus',
            options={'verbose_name': 'Event Status', 'verbose_name_plural': 'Event Status'},
        ),
        migrations.AlterModelOptions(
            name='managementteammember',
            options={'verbose_name': 'Management Team Member'},
        ),
        migrations.AlterModelOptions(
            name='salesteammember',
            options={'verbose_name': 'Sales Team Member'},
        ),
        migrations.AlterModelOptions(
            name='supportteammember',
            options={'verbose_name': 'Support Team Member'},
        ),
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
