# Generated by Django 3.2.9 on 2021-11-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20211118_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('prospect', 'prospect'), ('client', 'client')], default='prospect', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventstatus',
            name='status',
            field=models.CharField(max_length=150),
        ),
    ]
