# Generated by Django 3.2.9 on 2021-11-29 09:04


from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('auth', 'User')
    SalesTeamMember = apps.get_model('crm', 'SalesTeamMember')
    SupportTeamMember = apps.get_model('crm', 'SupportTeamMember')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    add_client = Permission.objects.get(codename='add_client')
    change_client = Permission.objects.get(codename='change_client')
    delete_client = Permission.objects.get(codename='delete_client')
    view_client = Permission.objects.get(codename='view_client')

    add_contract = Permission.objects.get(codename='add_contract')
    change_contract = Permission.objects.get(codename='change_contract')
    delete_contract = Permission.objects.get(codename='delete_contract')
    view_contract = Permission.objects.get(codename='view_contract')

    add_event = Permission.objects.get(codename='add_event')
    change_event = Permission.objects.get(codename='change_event')
    delete_event = Permission.objects.get(codename='delete_event')
    view_event = Permission.objects.get(codename='view_event')

    add_event_status = Permission.objects.get(codename='add_eventstatus')
    change_event_status = Permission.objects.get(codename='change_eventstatus')
    delete_event_status = Permission.objects.get(codename='delete_eventstatus')
    view_event_status = Permission.objects.get(codename='view_eventstatus')

    sales_permissions = [
        add_client,
        change_client,
        delete_client,
        view_client,
        add_contract,
        change_contract,
        delete_contract,
        view_contract,
        add_event,
        change_event,
        delete_event,
        view_event,
        add_event_status,
        change_event_status,
        delete_event_status,
        view_event_status,
    ]

    support_permissions = [
        view_client,
        view_contract,
        change_event,
        view_event,
        add_event_status,
        change_event_status,
        delete_event_status,
        view_event_status,
    ]

    sales = Group(name='Sales Team')
    sales.save()
    sales.permissions.set(sales_permissions)

    support = Group(name='Support Team')
    support.save()
    support.permissions.set(support_permissions)

    for user in User.objects.all():
        for sales_member in SalesTeamMember.objects.all():
            if user == sales_member.employee:
                sales.user_set.add(user)
        for support_member in SupportTeamMember.objects.all():
            if user == support_member.employee:
                support.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_delete_managementteammember'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]

